/* EJERCICIO INTEGRADOR FINAL - Script con Alter Table de la tabla Fact Ventas, en la que solo se realiza para generar las Foreign Key
una vez ya cargadas todas las tablas finales*/

USE DW_COMERCIAL

ALTER TABLE [dbo].[FACT_VENTAS]
ADD CONSTRAINT FK_PRODUCTO FOREIGN KEY (PRODUCTO_KEY)
REFERENCES [dbo].[DIM_PRODUCTO] (PRODUCTO_KEY)	;

ALTER TABLE [dbo].[FACT_VENTAS]
ADD CONSTRAINT FK_CATEGORIA FOREIGN KEY (CATEGORIA_KEY)
REFERENCES [dbo].[DIM_CATEGORIA] (CATEGORIA_KEY)	;

ALTER TABLE [dbo].[FACT_VENTAS]
ADD CONSTRAINT FK_CLIENTE FOREIGN KEY (CLIENTE_KEY)
REFERENCES [dbo].[DIM_CLIENTE] (CLIENTE_KEY)	;

ALTER TABLE [dbo].[FACT_VENTAS]
ADD CONSTRAINT FK_PAIS FOREIGN KEY (PAIS_KEY)
REFERENCES [dbo].[DIM_PAIS] (PAIS_KEY)	;

ALTER TABLE [dbo].[FACT_VENTAS]
ADD CONSTRAINT FK_VENDEDOR FOREIGN KEY (VENDEDOR_KEY)
REFERENCES [dbo].[DIM_VENDEDOR] (VENDEDOR_KEY)	;

ALTER TABLE [dbo].[FACT_VENTAS]
ADD CONSTRAINT FK_SUCURSAL FOREIGN KEY (SUCURSAL_KEY)
REFERENCES [dbo].[DIM_SUCURSAL] (SUCURSAL_KEY)	;

ALTER TABLE [dbo].[FACT_VENTAS]
ADD CONSTRAINT FK_TIEMPO FOREIGN KEY (TIEMPO_KEY)
REFERENCES [dbo].[DIM_TIEMPO] (TIEMPO_KEY)	;