/* EJERCICIO INTEGRADOR FINAL - Script con Validaciones y Supuestos. */

USE DW_COMERCIAL

-- Validaciones cantidad de registros En tablas Staging / Intermedias / Finales.

-- Tablas Producto.

SELECT * FROM STG_DIM_PRODUCTO
SELECT COUNT(*) CANTIDAD_REGISTROS FROM STG_DIM_PRODUCTO

SELECT * FROM INT_DIM_PRODUCTO
SELECT COUNT(*) CANTIDAD_REGISTROS FROM INT_DIM_PRODUCTO

SELECT * FROM DIM_PRODUCTO
SELECT COUNT(*) CANTIDAD_REGISTROS FROM DIM_PRODUCTO

-- Tablas Categoria.

SELECT * FROM STG_DIM_CATEGORIA
SELECT COUNT(*) CANTIDAD_REGISTROS FROM STG_DIM_CATEGORIA

SELECT * FROM INT_DIM_CATEGORIA
SELECT COUNT(*) CANTIDAD_REGISTROS FROM INT_DIM_CATEGORIA

SELECT * FROM DIM_CATEGORIA
SELECT COUNT(*) CANTIDAD_REGISTROS FROM DIM_CATEGORIA

-- Tablas Cliente.

SELECT * FROM STG_DIM_CLIENTE
SELECT COUNT(*) CANTIDAD_REGISTROS FROM STG_DIM_CLIENTE

SELECT * FROM INT_DIM_CLIENTE
SELECT COUNT(*) CANTIDAD_REGISTROS FROM INT_DIM_CLIENTE

SELECT * FROM DIM_CLIENTE
SELECT COUNT(*) CANTIDAD_REGISTROS FROM DIM_CLIENTE

-- Tablas Pais.

SELECT * FROM STG_DIM_PAIS
SELECT COUNT(*) CANTIDAD_REGISTROS FROM STG_DIM_PAIS

SELECT * FROM INT_DIM_PAIS
SELECT COUNT(*) CANTIDAD_REGISTROS FROM INT_DIM_PAIS

SELECT * FROM DIM_PAIS
SELECT COUNT(*) CANTIDAD_REGISTROS FROM DIM_PAIS

-- Tablas Vendedor.

SELECT * FROM STG_DIM_VENDEDOR
SELECT COUNT(*) CANTIDAD_REGISTROS FROM STG_DIM_VENDEDOR

SELECT * FROM INT_DIM_VENDEDOR
SELECT COUNT(*) CANTIDAD_REGISTROS FROM INT_DIM_VENDEDOR

SELECT * FROM DIM_VENDEDOR
SELECT COUNT(*) CANTIDAD_REGISTROS FROM DIM_VENDEDOR

-- Tablas Sucursal.

SELECT * FROM STG_DIM_SUCURSAL
SELECT COUNT(*) CANTIDAD_REGISTROS FROM STG_DIM_SUCURSAL

SELECT * FROM INT_DIM_SUCURSAL
SELECT COUNT(*) CANTIDAD_REGISTROS FROM INT_DIM_SUCURSAL

SELECT * FROM DIM_SUCURSAL
SELECT COUNT(*) CANTIDAD_REGISTROS FROM DIM_SUCURSAL

-- Tablas Ventas.

SELECT * FROM STG_FACT_VENTAS
SELECT COUNT(*) CANTIDAD_REGISTROS FROM STG_FACT_VENTAS

SELECT * FROM INT_FACT_VENTAS
SELECT COUNT(*) CANTIDAD_REGISTROS FROM INT_FACT_VENTAS

SELECT * FROM FACT_VENTAS
SELECT COUNT(*) CANTIDAD_REGISTROS FROM FACT_VENTAS

-- Cantidad Total Vendida y Monto Total Vendido.

SELECT SUM(CANTIDAD_VENDIDA) CANTIDAD_VENDIDA_TOTAL,SUM(MONTO_VENDIDO) MONTO_VENDIDO_TOTAL FROM INT_FACT_VENTAS

-- Validaciones de supuesto Producto / Categoría.

SELECT DISTINCT DESC_PRODUCTO, C.DESC_CATEGORIA FROM FACT_VENTAS V
JOIN DIM_CATEGORIA C ON C.CATEGORIA_KEY = V.CATEGORIA_KEY
JOIN DIM_PRODUCTO P ON P.PRODUCTO_KEY = V.PRODUCTO_KEY

-- Importes bajos de Comision Comercial.

SELECT MONTO_VENDIDO, COMISION_COMERCIAL, COMISION_COMERCIAL/MONTO_VENDIDO*100 PORCENTAJE
FROM FACT_VENTAS
WHERE COMISION_COMERCIAL/MONTO_VENDIDO*100 < 2

SELECT *
FROM FACT_VENTAS
WHERE COMISION_COMERCIAL/MONTO_VENDIDO*100 < 2

-- Valores negativos en registros de ventas

SELECT * FROM INT_FACT_VENTAS
WHERE MONTO_VENDIDO < 0

SELECT CANTIDAD_VENDIDA, PRECIO,  MONTO_VENDIDO, ROUND((CANTIDAD_VENDIDA * PRECIO*-1),2) MONTO_VENDIDO_POSITIVO
FROM INT_FACT_VENTAS
WHERE MONTO_VENDIDO <0

SELECT COD_PRODUCTO, COD_CATEGORIA,COD_CLIENTE,COD_PAIS,COD_VENDEDOR,COD_SUCURSAL,FECHA,CANTIDAD_VENDIDA,MONTO_VENDIDO*-1 MONTO_VENDIDO,PRECIO *-1 PRECIO,COMISION_COMERCIAL 
FROM INT_FACT_VENTAS
WHERE MONTO_VENDIDO <0

-- Métricas de Ventas.

SELECT SUM(MONTO_VENDIDO) MONTO_TOTAL_VENTAS, SUM(CANTIDAD_VENDIDA) CANTIDAD_VENDIDA, ROUND(AVG(MONTO_VENDIDO),2) MONTO_PROMEDIO_VENTAS,
SUM(COMISION_COMERCIAL) IMPORTE_COMISION_COMERCIAL
FROM FACT_VENTAS 

SELECT COUNT(*) CANTIDAD_CLIENTES FROM DIM_CLIENTE

-- Todas las métricas separadas.

SELECT SUM(MONTO_VENDIDO) MONTO_TOTAL_VENTAS FROM FACT_VENTAS
SELECT SUM(CANTIDAD_VENDIDA) CANTIDAD_VENDIDA FROM FACT_VENTAS
SELECT ROUND(AVG(MONTO_VENDIDO),2) MONTO_PROMEDIO_VENTAS FROM FACT_VENTAS
SELECT SUM(COMISION_COMERCIAL) IMPORTE_COMISION_COMERCIAL FROM FACT_VENTAS
SELECT COUNT(CLIENTE_KEY) CANTIDAD_CLIENTES FROM DIM_CLIENTE

-- Promedio de Ventas que coincide con el Excel, antes de las modificaciones, en la tabla INT_FACT_VENTAS.
SELECT ROUND(AVG(MONTO_VENDIDO),0) PROMEDIO_VENTAS FROM INT_FACT_VENTAS

-- Ventas determinadas / agrupadas por "tablas".

-- a) Un listado de los 17 productos, ordenados por Cantidad Total Vendida y en el caso de ser iguales, también por el Monto Total, en el cual nos indique
-- la Cantidad vendida durante todos estos años, el Monto Total y también el promedio del Precio y de la Comisión Comercial.

 SELECT DP.DESC_PRODUCTO, SUM(CANTIDAD_VENDIDA) CANTIDAD_TOTAL_VENDIDA,  SUM(MONTO_VENDIDO) MONTO_TOTAL_VENDIDO ,
 ROUND(AVG(PRECIO),2) PROMEDIO_PRECIO, ROUND(AVG(COMISION_COMERCIAL),2)  PROMEDIO_COMISION
 FROM FACT_VENTAS FV
 JOIN DIM_PRODUCTO DP ON DP.PRODUCTO_KEY=FV.PRODUCTO_KEY
GROUP BY DP.DESC_PRODUCTO
ORDER BY CANTIDAD_TOTAL_VENDIDA DESC, MONTO_TOTAL_VENDIDO

-- b) Consulta de las categorías mas vendidas, ordenadas en base a las que más venden e indicando su sucursal, a que país pertenece la misma
-- y la Cantidad vendida total junto al Monto Total de Ventas.

SELECT DC.DESC_CATEGORIA,DS.DESC_SUCURSAL, DP.DESC_PAIS, SUM(CANTIDAD_VENDIDA) CANTIDAD_VENDIDA_TOTAL, SUM(MONTO_VENDIDO) MONTO_VENDIDO_TOTAL 
FROM FACT_VENTAS FV
JOIN DIM_CATEGORIA DC ON DC.CATEGORIA_KEY=FV.CATEGORIA_KEY
JOIN DIM_SUCURSAL DS ON DS.SUCURSAL_KEY =FV.SUCURSAL_KEY
JOIN DIM_PAIS DP ON DP.PAIS_KEY=FV.PAIS_KEY
GROUP BY DC.DESC_CATEGORIA, DS.DESC_SUCURSAL,  DP.DESC_PAIS 
ORDER BY MONTO_VENDIDO_TOTAL DESC

-- c) Clientes que más compraron en monto total.

SELECT  CONCAT(NOMBRE,' ', APELLIDO) CLIENTE, SUM(MONTO_VENDIDO) MONTO_VENDIDO, SUM(CANTIDAD_VENDIDA) CANTIDAD_VENDIDA
FROM FACT_VENTAS FV
JOIN DIM_CLIENTE DC ON DC.CLIENTE_KEY=FV.CLIENTE_KEY
GROUP BY CONCAT(NOMBRE,' ', APELLIDO)
ORDER BY MONTO_VENDIDO DESC, CANTIDAD_VENDIDA

-- d) Top 25 de Vendedores que más vendieron en Monto, por año.

SELECT TOP(25) CONCAT(NOMBRE,' ', APELLIDO) VENDEDOR, SUM(MONTO_VENDIDO) MONTO_VENDIDO, ANIO
FROM FACT_VENTAS FV
JOIN DIM_VENDEDOR DV ON DV.VENDEDOR_KEY=FV.VENDEDOR_KEY
JOIN DIM_TIEMPO DT ON DT.TIEMPO_KEY = FV.TIEMPO_KEY
GROUP BY  MONTO_VENDIDO, CONCAT(NOMBRE,' ', APELLIDO), ANIO
ORDER BY MONTO_VENDIDO DESC

-- e) Paises con menor comisión desde 2016 a 2021.

SELECT SUM(COMISION_COMERCIAL) TOTAL_COMISION_COMERCIAL,  DESC_PAIS
FROM FACT_VENTAS FV
JOIN DIM_PAIS DP ON DP.PAIS_KEY = FV.PAIS_KEY
GROUP BY DESC_PAIS
ORDER BY TOTAL_COMISION_COMERCIAL ASC

-- f) Ranking de los 20 meses en que más se vendió, por país.

SELECT TOP(20) SUM(MONTO_VENDIDO) MONTO_VENDIDO, DESC_PAIS, MES_NOMBRE , ANIO
FROM FACT_VENTAS FV
JOIN DIM_TIEMPO DT ON DT.TIEMPO_KEY = FV.TIEMPO_KEY
JOIN DIM_PAIS DP ON DP.PAIS_KEY = FV. PAIS_KEY
GROUP BY ANIO, DESC_PAIS, MES_NOMBRE
ORDER BY MONTO_VENDIDO DESC, ANIO -- Año más viejo primero, porque si bien no estamos haciendo un análisis inflacionario ya que no contamos
								  -- con los datos necesarios, se supone que en latinoamerica siempre hay inflación y que en caso de igualdad de ventas
								  -- el año más antiguo sería el que más "vendió" o beneficio dió.

